config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  get 'submissions/:id/verify' => 'submissions#verify'
  resources :projects
  post 'projects/import' => 'projects#import'

  devise_for :users
  devise_for :admins
  devise_for :students

  resources :admins, only: [:index]
  resources :students, only: [:index]

  #get 'dashboard' => 'dashboard#index', as: "user_root_path"
  #get 'dashboard/admin' => 'dashboard#admin', as: "admin_root_path"
  #get 'dashboard/student' => 'dashboard#student', as: "student_root_path"
  root to: 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index

  end

  def student
    authenticate_student!
    student = current_student
    @submissions = student.submissions
  end

  def admin
    authenticate_admin!
    @projects = current_admin.projects
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_header.html.erb
<div class="toggle-nav">
  <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
</div>

<!--logo start-->
<a href="index.html" class="logo">IIITB Assessment Portal</a>
<div class="top-nav notification-row">
  <!-- notificatoin dropdown start-->
  <ul class="nav pull-right top-menu">

    <!-- task notificatoin start -->
    <!--<li id="task_notificatoin_bar" class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <i class="icon-task-l"></i>
        <span class="badge bg-important">6</span>
      </a>
      <ul class="dropdown-menu extended tasks-bar">
        <div class="notify-arrow notify-arrow-blue"></div>
        <li>
          <p class="blue">You have 6 pending letter</p>
        </li>
        <li>
          <a href="#">
            <div class="task-info">
              <div class="desc">Design PSD </div>
              <div class="percent">90%</div>
            </div>
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                <span class="sr-only">90% Complete (success)</span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="#">
            <div class="task-info">
              <div class="desc">
                Project 1
              </div>
              <div class="percent">30%</div>
            </div>
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%">
                <span class="sr-only">30% Complete (warning)</span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="#">
            <div class="task-info">
              <div class="desc">Digital Marketing</div>
              <div class="percent">80%</div>
            </div>
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                <span class="sr-only">80% Complete</span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="#">
            <div class="task-info">
              <div class="desc">Logo Designing</div>
              <div class="percent">78%</div>
            </div>
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%">
                <span class="sr-only">78% Complete (danger)</span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="#">
            <div class="task-info">
              <div class="desc">Mobile App</div>
              <div class="percent">50%</div>
            </div>
            <div class="progress progress-striped active">
              <div class="progress-bar"  role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                <span class="sr-only">50% Complete</span>
              </div>
            </div>

          </a>
        </li>
        <li class="external">
          <a href="#">See All Tasks</a>
        </li>
      </ul>
    </li>-->
    <!-- task notificatoin end -->
    <!-- inbox notificatoin start-->
    <!--<li id="mail_notificatoin_bar" class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <i class="icon-envelope-l"></i>
        <span class="badge bg-important">5</span>
      </a>
      <ul class="dropdown-menu extended inbox">
        <div class="notify-arrow notify-arrow-blue"></div>
        <li>
          <p class="blue">You have 5 new messages</p>
        </li>
        <li>
          <a href="#">
            <span class="photo"><img alt="avatar" src="./img/avatar-mini.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Greg  Martin</span>
                                    <span class="time">1 min</span>
                                    </span>
                                    <span class="message">
                                        I really like this admin panel.
                                    </span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="photo"><img alt="avatar" src="./img/avatar-mini2.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Bob   Mckenzie</span>
                                    <span class="time">5 mins</span>
                                    </span>
                                    <span class="message">
                                     Hi, What is next project plan?
                                    </span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="photo"><img alt="avatar" src="./img/avatar-mini3.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Phillip   Park</span>
                                    <span class="time">2 hrs</span>
                                    </span>
                                    <span class="message">
                                        I am like to buy this Admin Template.
                                    </span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="photo"><img alt="avatar" src="./img/avatar-mini4.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Ray   Munoz</span>
                                    <span class="time">1 day</span>
                                    </span>
                                    <span class="message">
                                        Icon fonts are great.
                                    </span>
          </a>
        </li>
        <li>
          <a href="#">See all messages</a>
        </li>
      </ul>
    </li>
    --><!-- inbox notificatoin end -->
    <!-- alert notification start-->
    <!--<li id="alert_notificatoin_bar" class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">

        <i class="icon-bell-l"></i>
        <span class="badge bg-important">7</span>
      </a>
      <ul class="dropdown-menu extended notification">
        <div class="notify-arrow notify-arrow-blue"></div>
        <li>
          <p class="blue">You have 4 new notifications</p>
        </li>
        <li>
          <a href="#">
            <span class="label label-primary"><i class="icon_profile"></i></span>
            Friend Request
            <span class="small italic pull-right">5 mins</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-warning"><i class="icon_pin"></i></span>
            John location.
            <span class="small italic pull-right">50 mins</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-danger"><i class="icon_book_alt"></i></span>
            Project 3 Completed.
            <span class="small italic pull-right">1 hr</span>
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-success"><i class="icon_like"></i></span>
            Mick appreciated your work.
            <span class="small italic pull-right"> Today</span>
          </a>
        </li>
        <li>
          <a href="#">See all notifications</a>
        </li>
      </ul>
    </li>
    --><!-- alert notification end-->
    <!-- user login dropdown start-->
    <% if current_admin.nil? %>
      <%= render 'dashboard/userbox'%>
    <% else%>
      <%= render 'dashboard/adminbox'%>
    <%end%>

    <!-- user login dropdown end -->
  </ul>
  <!-- notificatoin dropdown end-->
</div>

app/views/dashboard/_sidebar.html.erb
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu">
      <li class="active">
        <a class="" href="index.html">
          <i class="icon_house_alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
    </ul>   <!-- sidebar menu end-->
  </div>
</aside>

app/views/dashboard/_userbox.html.erb
<li class="dropdown">
  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="img/avatar1_small.jpg">
                            </span>
    <span class="username"><%= current_student.email%>></span>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu extended logout">
    <div class="log-arrow-up"></div>
    <li class="eborder-top">
      <a href="#"><i class="icon_profile"></i> My Profile</a>
    </li>
    <li>
      <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
    </li>
    <li>
      <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
    </li>
    <li>
      <a href="#"><i class="icon_chat_alt"></i> Chats</a>
    </li>
    <li>
      <%= link_to('Logout', destroy_student_session_path, :method => :delete) %>
    </li>
    <li>
      <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
    </li>
    <li>
      <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
    </li>
  </ul>
</li>

app/views/dashboard/admin.html.erb
<% if admin_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
    </li>
<% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
    </li>
<% end %>

Hello <%= current_admin.email %>

<%= render 'projects/index'%>

app/views/dashboard/index.html.erb
Hello User

app/views/dashboard/student.html.erb
<div class="row">
  <div class="col-lg-6 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box blue-bg">
      <i class="fa fa-cloud-download"></i>
      <div class="count"><%= current_student.submissions.where(status: 0).count %></div>
      <div class="title">Pending Submissions</div>
    </div><!--/.info-box-->
  </div><!--/.col-->

  <div class="col-lg-6 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box brown-bg">
      <i class="fa fa-shopping-cart"></i>
      <div class="count"><%= current_student.submissions.where(status: 1).count %></div>
      <div class="title">Completed</div>
    </div><!--/.info-box-->
  </div><!--/.col-->

</div><!--/.row-->
<%= render 'submissions/index' %>