config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  get 'submissions/:id/verify' => 'submissions#verify'
  resources :projects
  post 'projects/import' => 'projects#import'

  devise_for :users
  devise_for :admins
  devise_for :students

  resources :admins, only: [:index]
  resources :students, only: [:index]

  #get 'dashboard' => 'dashboard#index', as: "user_root_path"
  #get 'dashboard/admin' => 'dashboard#admin', as: "admin_root_path"
  #get 'dashboard/student' => 'dashboard#student', as: "student_root_path"
  root to: 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
  BASE_URL = 'http://localhost:5000'
  belongs_to :student
  belongs_to :project

  validate :student
  validate :project

  # TODO: Add validations and hooks

  validates_uniqueness_of :student_id, :scope => :project_id

  before_create :generate_tag

  # Connects with docker repository to find the image.
  def verify
    # TODO: See if there is a better way to do this.
    response = HTTParty.get(BASE_URL + "/v2/_catalog")
    puts response.body

    json = JSON.parse(response.body)

    r = json['repositories']

    if r.include? self.image_tag
      self.status = SUBMISSION_VERIFIED
      return self.save
    else
      errors.add(:base, "Image hasn't been uploaded yet.")
      return false
    end
  end

  # Generate tag to be used by students for submission
  def generate_tag
    # TODO: Add a random 4 letter text here
    self.image_tag = "#{self.project.id.to_s}/#{self.student.id.to_s}"
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy, :verify]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  def verify
    if @submission.verify
      redirect_to :back, notice: 'Submission was successfully verified.'
    else
     redirect_to :back, notice: 'Unable to verify the image upload.'
    end
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:project_id, :student_id, :comments)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(submission) do |f| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.number_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.number_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_field :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Project</th>
      <th>Student</th>
      <th>Tag</th>
      <th>Start time</th>
      <th>End Time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.project.name %></td>
        <td><%= submission.student.email %></td>
        <td><%= submission.image_tag %></td>
        <td><%= submission.project.start_time %></td>
        <td><%= submission.project.end_time %></td>
        <td><%= submission.status %></td>
        <td><%= link_to "Verify Submission", "/submissions/#{submission.id}/verify"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/submissions/_show.html.erb
<% if !@submission.nil? %>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Project:</strong>
      <%= @submission.project_id %>
      <%= @submission.project.name %>
    </p>

    <p>
      <strong>Student:</strong>
      <%= @submission.student_id %>
    </p>

    <p>
      <strong>Comments:</strong>
      <%= @submission.comments %>
    </p>

    <%= link_to 'Edit', edit_submission_path(@submission) %> |
    <%= link_to 'Back', submissions_path %>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Project</th>
      <th>Student</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.project_id %></td>
        <td><%= submission.student_id %></td>
        <td><%= submission.comments %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @submission.project_id %>
  <%= @submission.project.name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @submission.student_id %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @submission.comments %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>