config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  get 'submissions/:id/verify' => 'submissions#verify'
  resources :projects
  post 'projects/import' => 'projects#import'

  devise_for :users
  devise_for :admins
  devise_for :students

  resources :admins, only: [:index]
  resources :students, only: [:index]

  #get 'dashboard' => 'dashboard#index', as: "user_root_path"
  #get 'dashboard/admin' => 'dashboard#admin', as: "admin_root_path"
  #get 'dashboard/student' => 'dashboard#student', as: "student_root_path"
  root to: 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :admin
  has_many :submissions

  # Validations
  validate :admin
  validates_presence_of :name

  before_create :validate_dates


  # TODO: Add validations and hooks

  def validate_dates
    puts "Start", start_time
    puts "End", end_time
    if start_time > end_time
      errors.add(:base, "End time can't be earlier than start time")
      return false
    end
  end

  # Add submission for multiple students
  def add_students students
    students.each do |s|
      add_student s
    end
  end

  # Add a submission for a student for this project
  def add_student student
    s = Submission.new(project: self, student: student)
    self.submissions << s
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_admin.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def import
    @project = Project.find(params[:project_id])
    myfile = params[:file]
    students = []

    CSV.foreach(myfile.path) do |row|
      s= Student.find_by_email(row[0])
      if s.nil?
        puts "Student not found"
      else
        students << s
      end
    end


    render json: students
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:admin_id, :name, :start_time, :end_time)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
    <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :admin_id %>
      <%= f.collection_select(:admin_id, Admin.all, :id, :email, :prompt => 'Select') %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :start_time %>
      <%= f.datetime_local_field :start_time %>
    </div>

    <div class="field">
      <%= f.label :end_time %>
      <%= f.datetime_local_field :end_time %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/projects/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Admin</th>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.admin_id %></td>
        <td><%= project.name %></td>
        <td><%= project.start_time %></td>
        <td><%= project.end_time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @project.admin_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @project.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @project.end_time %>
</p>

<% @students = Student.where(student: @project.submissions.select(:student_id)) %>

<%= render 'students/index'%>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Admin</th>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.admin_id %></td>
        <td><%= project.name %></td>
        <td><%= project.start_time %></td>
        <td><%= project.end_time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @project.admin_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @project.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @project.end_time %>
</p>

<% @submissions = @project.submissions %>



Add Students to this project
<%= form_tag('/projects/import', multipart: true) do %>
    <input type="text" hidden="true" name="project_id" value="<%= @project.id %>">
           <%= file_field_tag :file %>
           <%= submit_tag( "Import" ) %>
<% end %>

<%= render 'submissions/index'%>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>